modified README.md, added index.html,style.css and linters
maserekafelex/Mobile-porto-1 pull request #1
Opened 2023-04-25 14:52 UTC by maserekafelex

modified README.md
added index.html,style.css and linters

2023-04-25 15:29 UTC, iambenkis requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @maserekafelex  
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Follow GitHub flow :heavy_check_mark: 

## Required changes :recycle: :recycle: 

- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me @iambenkis  when you comment, so I can receive the notification or use Slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-25 15:29 UTC, iambenkis commented on style.css
> +  }
- [ ] Good job implementing the first page of your portfolio 👍 , however as requested the requirements 🤙 , you should align these two sections with `flexbox` 😄 , Kindly apply that 👍 

![Captureb](https://user-images.githubusercontent.com/80458199/234325269-20081024-4e3a-44d5-ae0c-9bb32900506a.JPG)

2023-04-25 15:29 UTC, iambenkis commented on index.html
> +                </ul>
- [ ] THe requirement said that you should make sure your design look the same as the Figma design 😄 , that means margin, padding , fonts, should stick with each other . Kindly update the margin left of your design as represented on the picture below to stick to the Figma design 😄 

| ### Your design  |  ### Figma Desing | 
| :---: | :---: |
| ![Capture](https://user-images.githubusercontent.com/80458199/234326392-d80e56d0-a81e-4872-998d-87b6b660cb6f.JPG) | ![Capture 1](https://user-images.githubusercontent.com/80458199/234326432-cb0db02e-0f2a-4ce3-ab77-1b1116ff0433.JPG) |

2023-04-25 15:29 UTC, iambenkis commented on README.md
> -<p align="right">(<a href="#readme-top">back to top</a>)</p>
- [ ] [OPTIONAL] This note is only instructions for you to set up the license. I think you should remove it to keep your readme looking professional.

2023-04-25 19:09 UTC, Zuhaib042 requested changes
Hi @maserekafelex 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![](https://media.giphy.com/media/z3piokwf0WPH81MOhu/giphy.gif)

 ## Highlights
✅ Correct Github flow
✅ Descriptive PR

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-25 19:09 UTC, Zuhaib042 commented on style.css
> +  }
- [ ] As suggested by the previous reviewer, Kindly consider applying flex in this container to fulfill the requirement and to align the elements in the headline section with flex. 
I can see that you have applied flex in the toolbar(navbar) section but here you must apply display: flex as well to fulfill the requirement.

2023-04-25 19:09 UTC, Zuhaib042 commented on README.md
>  > Give credit to everyone who inspired your codebase.
- [OPTIONAL] Kindly consider removing this line as this is referred to you and not to the visitor of your repo. removing it will make your repo more professional.

2023-04-25 19:09 UTC, Zuhaib042 commented on README.md
>  - [ ] **[new_feature_3]**
- [OPTIONAL] Kindly consider adding at least 1 or 2 future features  in your readme to make it look more professional.

2023-04-25 19:09 UTC, Zuhaib042 commented on style.css
> +@media screen and (min-width: 350px) {
- [OPTIONAL] As we are instructed to follow a Mobile-first approach, in which we style the mobile design first without using any media queries. then when we have to style the desktop version, we use media queries. so you can consider removing the media query for now and then adding a `min-width: 768px` media query later when you style the desktop screens.

2023-04-26 09:38 UTC, usorfaitheloho approved these changes
Hi @maserekafelex 👋,

# STATUS: APPROVED 🕺🥳 

Congratulations🍾🥳!! Your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

![](https://media.giphy.com/media/l49JNZ87F3AmPoH0A/giphy.gif)

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-26 10:20 UTC, merged