Portfolio menu
maserekafelex/Mobile-porto-1 pull request #7
Opened 2023-05-23 13:35 UTC by maserekafelex

I have modified index.html with style.css
I have also added index.js to hold the javaScript content
I have also modified the linters

2023-05-23 16:57 UTC, levy002 requested changes
## Hello @maserekafelex   , :wave:
### I'm Levy, your PR reviewer

Good job so far :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)

## Highlights
- No linter error :heavy_check_mark: 

## Status: REQUIRED CHANGES ♻️
_Check the comments under the review._


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @levy002 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-23 16:57 UTC, levy002 commented on index.html
> +    </li>
- [ ] Kindly make sure when the nav link is clicked after closing the mobile menu, the corresponding part appears directly on the page. If we click the `About` button, the About section must be displayed directly. Kindly fix that.

2023-05-23 16:57 UTC, levy002 commented on style.css
> +}
- [ ] Kindly make sure your link's typography matches the provided Figma design as much as possible. Kindly use the correct `font-family` and `font-weight` in order to match the provided Figma design.

   - ### YOUR DESIGN
   
     ![image](https://github.com/maserekafelex/Mobile-porto-1/assets/87197412/59bcb541-35db-4ca2-bb1f-59ec46de2dd1)

   - ### FIGMA DESIGN
   
    ![image](https://github.com/maserekafelex/Mobile-porto-1/assets/87197412/83a2ef56-b28e-43c3-8f3c-df93f50a97ec)

2023-05-23 16:57 UTC, levy002 commented on style.css
> +}
- [ ] Kindly make sure to use the same background-color as in order to match the provided Figma design as much as possible.

- [ ] Kindly make sure to remove the top white space on the top of the mobile menu container because it should cover all visible screen with its background color.


   - ###  YOUR DESIGN
    ![image](https://github.com/maserekafelex/Mobile-porto-1/assets/87197412/9b1193cb-7a0d-4f5b-b63a-f3251b974007)

   - ### FIGMA DESIGN
   
    ![image](https://github.com/maserekafelex/Mobile-porto-1/assets/87197412/153589d8-e5f8-4454-a0d4-4d1b60b45c91)

2023-05-23 16:57 UTC, levy002 commented on index.html
> +    </div>
- [ ] Kindly make sure we can still be able to see the `close` menu button even if we scroll and it can be visible as how it is visible on the provided design. Make sure to adjust the spacing around it in order to position it correctly in order to match the provided Figma design.

   - ### YOUR DESIGN
    ![chrome-capture-2023-4-23](https://github.com/maserekafelex/Mobile-porto-1/assets/87197412/0c65e462-a550-431e-bc22-823012e7105d)

   - ### FIGMA DESIGN
   ![image](https://github.com/maserekafelex/Mobile-porto-1/assets/87197412/8b36b7d0-e0fe-4cf8-a982-c7941cc5dc58)

2023-05-23 22:41 UTC, brainconnect93 requested changes
## STATUS: Changes Required :recycle:

### Hi @maserekafelex, 👋 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.tenor.com/isiLRnxz3zwAAAAM/cat-driving-serious.gif" width="500px" height="300px">

## To Highlight 👍

- Descriptive Pull Request title and summary. ✔️
- Has Hamburger Menu functionality ✔️
- Mobile menu options, the correct part of the page is displayed ✔️
- Good use of Github flow ✔️
### Changes Required

- [ ]  _Please check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @brainconnect93 ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-23 22:41 UTC, brainconnect93 commented on index.html
> +    </div>
- [ ] Hello @maserekafelex , I notice whilst trying to work on the changes requested by the previous reviewer, You have introduced another bug in your project. Currently i can't see the `hamburger` icon in your project and it makes it difficult for me to assess your project to see whether you have actually worked on the changes requested by the previous reviewer.

Below is the video to my claim 👇 


https://github.com/maserekafelex/Mobile-porto-1/assets/78634841/7041266b-b6d4-4a1a-99cf-627c93bdbd93

2023-05-24 05:48 UTC, shella12 approved these changes
Hi @maserekafelex and @AbednegoKibitok, 


## Status : APPROVED 🥳 🥳 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif"/>

## Highlights

- Each link is navigates to expected section ✔️ 
- Menu closes on clicking (X) 👍 
- Menu opens on clicking `hamburger-icon` 👏 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-24 05:48 UTC, shella12 commented on style.css
> +  transition: 0s;
- [ ] [OPTIONAL] Great job on your mobile menu it almost looks quite identical to the provided design however I would highly recommend you to add a bit of padding to give space to the elements 

|Your design| Figma design|
|----|-----|
|<img width="484" alt="Screenshot 2023-05-24 at 10 39 45 AM" src="https://github.com/maserekafelex/Mobile-porto-1/assets/44798044/285afbc9-e02b-41a9-b656-500ac3a3cef6">|<img width="393" alt="Screenshot 2023-05-24 at 10 42 47 AM" src="https://github.com/maserekafelex/Mobile-porto-1/assets/44798044/96cb1a3e-200f-4e68-bad1-8644f1d43550">|

2023-05-24 05:48 UTC, shella12 commented on index.js
> +}));
- [ ] [OPTIONAL] I would highly suggest you to make your mobile menu disappear when user expands to the desktop menu for better user experience

<img width="967" alt="Screenshot 2023-05-24 at 10 43 46 AM" src="https://github.com/maserekafelex/Mobile-porto-1/assets/44798044/25999e00-f0ad-43e9-bd8a-2aa7ebeb0e9c">

2023-05-24 05:54 UTC, merged